### ISSUE TITLE
how do we work with imports

### ISSUE THREAD

**Issue by cjmash** [hashicorp/terraform-guides#11]
i'm not sure if this is an issue 
i have a code policy.sentinel

> import "tfplan"
> allowed_machine_types = [
>     "n1-standard-1",
>     "n1-standard-2",
>     "n1-standard-4",
>     "n1-standard-8",
> ]
> 
> main = rule {
>     all tfplan.resources as type, resources {
>         all resources as r {
>             r.applied.machine_type in allowed_machine_types
>         }
>     }
> }

then i have config.json 

> {
> "imports": {
>     "tfplan": {
>         "path": "terraplan"
>         }
>     }
> }
> 
where terraplan is an executable file generrated when i run 
`terraform plan -out terraplan`
when i run sentinel apply -config=config policy.sentinel
i get this error 
```
Runtime error while running the policy:

test.sentinel:1:1: exec: "terraform": executable file not found in $PATH

A runtime error is a non-recoverable error and always represents a bug
in the policy. When a runtime error is experienced, the result of the
policy is "false". Please fix the error above and try again.
```

what could i be doing wrong??

**Comment by rberlind** [comment]
Hi @cjmash:

It sounds like you are trying to use the Sentinel Simulator to test a Terraform Sentinel policy.  Unfortunately, Terraform Sentinel policies cannot currently be tested with the Sentinel simulator because some of the Terraform Sentinel functions cannot be mocked by it.  Terraform Sentinel policies can currently only be used with Terraform Enterprise (TFE).  If you have access to TFE, you can test a Sentinel policy by triggering a run in TFE against a workspace that tries to create resources such as google_compute_instance that have the machine_type attribute.  You can then discard the run if you do not actually want to apply any changes.

Note that this policy would be more efficient if you restricted it to just resources of type google_compute_instance (assuming that is what you are testing) as is done in https://github.com/hashicorp/terraform-guides/blob/master/governance/gcp/restrict-machine-type.sentinel.  Note that this version of the policy also has the advantage of testing all modules, not just the root module.
