### ISSUE TITLE
restrict-assumed-role-by-workspace.sentinel policy throws some syntax error when module in terraform used

### ISSUE THREAD

**Issue by npravi2003** [hashicorp/terraform-guides#198]
while apply sentinel policy "restrict-assumed-role-by-work space" throws an syntax error as below 

An error occurred: aws-apps/restrict-assumed-role-by-workspace.sentinel:28:15: only a list or map can be indexed, got undefined
<img width="879" alt="sentinel policy error" src="https://user-images.githubusercontent.com/41763394/78835310-955a8380-79b5-11ea-9994-caa6229e470f.PNG">

The below code of line has some issues especially the highlighted one.
 
```
  for tfconfig.module_paths as path {
    # Iterate over providers of given type in module
    aliases = tfconfig.module(path).providers[type]["alias"] else {}         ###This is the line number gets the error####
    for aliases as alias, data {
      # Change default alias ("") to "default"
      if alias is "" {
        alias = "default"
      }
      # Get the address of the provider alias
      if length(path) == 0 {
        # root module
        address =  type + "." + alias
      } else {
        # non-root module
        address = "module." + strings.join(path, ".module.") + "." +
                  type + "." + alias
      }
      providers[address] = data
    } // end aliases loop
  } // end module_paths loop
  return providers
}
```

Can someone look this into and help me to resolve it. Thanks.

**Comment by npravi2003** [comment]
An error occurred: aws-apps/restrict-assumed-role-by-workspace.sentinel:28:15: only a list or map can be indexed, got undefined

<img width="879" alt="sentinel policy error" src="https://user-images.githubusercontent.com/41763394/78834529-5415a400-79b4-11ea-88e4-385ce85e24fe.PNG">

**Comment by npravi2003** [comment]
##### Functions #####

# Find all providers aliases of given type using the tfconfig import
find_provider_aliases = func(type) {

  # We will find all provider aliases og given type from tfconfig,
  # meaning providers.TYPE.alias.ALIAS
  providers = {}

  # Iterate over all modules in the tfconfig import
  for tfconfig.module_paths as path {
    # Iterate over providers of given type in module
    aliases = tfconfig.module(path).providers[type]["alias"] else {}         ###This is the line number gets the error####
    for aliases as alias, data {
      # Change default alias ("") to "default"
      if alias is "" {
        alias = "default"
      }

      # Get the address of the provider alias
      if length(path) == 0 {
        # root module
        address =  type + "." + alias
      } else {
        # non-root module
        address = "module." + strings.join(path, ".module.") + "." +
                  type + "." + alias
      }

      providers[address] = data

    } // end aliases loop
  } // end module_paths loop

  return providers
}


Can someone look this into and help me to resolve it. Thanks.

**Comment by rberlind** [comment]
@npravi2003 : I'm so sorry that I never saw this issue for the past 10 months.  I need to configure this repository so that I am notified when people report issues, especially about the Sentinel policies that I have written.

In any case, it looks like you were using the second generation of the policy.  I recommend using the third-generation version which is [here](https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/aws/restrict-assumed-roles-by-workspace.sentinel).

That version does need Terraform 0.12 or higher.  If you are still using Terraform 0.11, let me know and I will look at fixing the second-generation version.

Again, apologies for the unaccaptable delay in my response.
Roger Berlind
Global Technology Specialist
HashiCorp

**Comment by rberlind** [comment]
Closing this since I did not hear back from @npravi2003
