### ISSUE TITLE
moving resources from one resource group to another resource group

### ISSUE THREAD

**Issue by vsai9594** [hashicorp/terraform-guides#232]
can we move a azure resource from one resource group to another using terraform?

**Comment by rberlind** [comment]
@vsai9594 : Apologies that noone from HashiCorp answered this a long time ago.
It is probably better to ask questions like this in https://discuss.hashicorp.com/.

In any case, the Azure provider docs like https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#resource_group_name say that changing the `resource_group_name` of resources requires a new one to be created. So, I do not think you could do what you want with Terraform by itself.

I do see https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription from Microsoft which gives powershell and CLI commands to move resources between resource groups and even subscriptions.  But if you did that for resources created for Terraform, the next plan or apply would probably try to change the resource group back since Terraform is declarative.

However,  the following 3-step approach should work:

1. Use Microsoft's API, CLI, or powershell to move the resource to a different resource group.
2. Then modify the Terraform configuration to use the new resource group in `resource_group_name`.
3. Run `terraform refresh` against the workspace or configuration to force Terraform to update the state file with the new resource group.

Then the next plan would see that the resource group name in the Terraform code matches the updated state and not need to make any changes.

Roger Berlind
Global Technology Specialist
HashiCorp

**Comment by audunsolemdal** [comment]
For any googlers: The method described does not work, at least not for latest tf / provider versions.

**Comment by rapolas-oag** [comment]
I had to changes this a bit, and add one more step:
1. Create new resource group and app plan;
2. Manually transfer app plan to an old resource group;
3. Amend tf for app plan to be within an old resource group;
4. Refresh tf (add -refresh-only to plan and apply), basically to delete from tfstate moved app plan;
5. Use import and all its magic with new import block ([documentation](https://developer.hashicorp.com/terraform/language/import)):
```
import {
  to = aws_instance.example
  id = "i-abcd1234"
}

resource "aws_instance" "example" {
  name = "hashi"
  # (other resource arguments...)
}
```
