### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by prathjan** [hashicorp/terraform-guides#276]
Hi @rberlind - I generated the API token, specified variables.csv and ran with a sample git repo. I get the following error:
KeyError: 'data'
Run Status: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'data'
Run can be applied: 
We will sleep and try again soon.
Checking run status
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'data'
Run Status: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'data'
Run can be applied: 
We will sleep and try again soon.
Checking run status
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'data'
Run Status: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'data'
Run can be applied:

**Comment by prathjan** [comment]
@beneduwensuyi

**Comment by rberlind** [comment]
@prathjan : could you clarify when this happened?  Which script were you running?

**Comment by prathjan** [comment]
@rberlind I am running your automation scripts with my own git repo: ./loadAndRunWorkspace.sh https://github.com/prathjan/iks-intersight-terraform.git. 

I have a variables.tf file where I have declared this variable:
variable "api_key_id" {
  type = string 
}

And access it in my main.tf:
provider "intersight" {
  apikey        = var.api_key_id
  secretkey = var.api_private_key
  endpoint      = var.api_endpoint
}

Bt, I get an error when I run your automation script:
Getting the result of the Terraform Plan.
Plan Log:
Terraform v0.11.14

Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2021/03/03 00:03:19 [DEBUG] Using modified User-Agent: Terraform/0.11.14 TFC/c998a84844
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /terraform/cprofile.tf: At 18:19: Unknown token: 18:19 IDENT var.api_key_id


Finished

**Comment by prathjan** [comment]
@rberlind it works when I run on command line

**Comment by rberlind** [comment]
@prathjan : Sorry for not getting back to you sooner.

So, now I understand which script you are running (https://github.com/hashicorp/terraform-guides/blob/master/operations/automation-script/loadAndRunWorkspace.sh), but I'm a bit confused by your most recent post which said it works when you run it on a command line.

Does that mean you no longer need help with this?

If you do still need help, can you clarify how you ran the script when it did give you errors and show the exact command you used to run it? And can you explain how that is different from running it on the command line?  Ideally, you would show the full output from that command, possibly after scrubbing any sensitive data.

I suspect you are talking about a difference between loading your Terraform configuration from a local directory in the config directory where the script lives vs. loading it from your repository. Is that correct?

Thanks,
Roger Berlind

**Comment by prathjan** [comment]
@rberlind is there a slack channel that we can connect on? I still see issues in using this script

**Comment by prathjan** [comment]
@rberlind I ran with one of your own examples:

./loadAndRunWorkspace.sh https://github.com/hashicorp/learn-state-migration
TFE_TOKEN environment variable was found.
TFE_ORG environment variable was set to CiscoDevNet.
Using organization, CiscoDevNet.
TFE_ADDR environment variable was not set.
Using Terraform Cloud (TFE SaaS) address, app.terraform.io.
If you want to use a private TFE server, export/set TFE_ADDR.
Cloning from git URL https://github.com/hashicorp/learn-state-migration into directory learn-state-migration
Using workspace set in the script.
override not set on command line. Will not override.
Tarring configuration directory.
Checking to see if workspace exists
Workspace ID:  ws-GmAhz1KFwZ45b5Pd
Workspace already existed.
Creating configuration version.
Config Version ID:  cv-NCfdqLgLE7PzDiHs
Upload URL:  https://archivist.terraform.io/v1/object/dmF1bHQ6djE6enFPa3NNQUVBT3dqMzhyeG5qdjYySTh0dy9ZLzM4VXBtTERCYW1PazlkbERaZWVweDIzNDZxNko0OWhmQjZjc3dBb0tGS2txQVFQQ2lIRTRzNHdVOExtV21CbmtwKzBhenNWWmdURHEvQkg0M1JMSk5wejBmVkpmRjh4VkF4MWdLWEFkajhPYWpxaHRvQjVkRzBCcEhETDVUNnhYeEhESTMxcnMrMGFZTjhreEZQZU5UV00yMG1IbFpvSjhxVVB5aTE2MnMrRy82Qm9oaEhad3kxdi80TXVITHQwWmRqajMwcXFabkJWb2dvazhRYllFNWovV1ZKWXZ2MWg1aVlCWEVZRTMwNkEyeTdQL0VaSlhEcUVwblpaV0w2cTVNZ2M9
Uploading configuration version using learn-state-migration.tar.gz
Did not find variables.csv in configuration.
Will load variables from ./variables.csv
Adding variable name with value Roger in category terraform with hcl false and sensitive false
Adding variable TF_CLI_ARGS with value -no-color in category env with hcl false and sensitive false
Number of Sentinel policies:  0
Run ID:  run-Xs35Tp8CKFrMJCmr
Checking run status
Run Status:  errored
Run can be applied:  False
Plan errored or hard-mandatory policy failed
Getting the result of the Terraform Plan.
Plan Log:
Terraform v0.11.14

Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2021/03/04 18:58:43 [DEBUG] Using modified User-Agent: Terraform/0.11.14 TFC/c998a84844
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /terraform/main.tf: At 9:15: Unknown token: 9:15 IDENT var.name_length


Finished

**Comment by rberlind** [comment]
I do not have a Slack channel to use for this issue, @prathjan.
Please do try to answer my most recent questions so I can better assist you.

Also, it occurs to me now that when you wrote, "it works when I run on command line", that you might have meant that you are able to run `terraform plan` and `terraform apply` against your Terraform configuration when not using the script.

But I do need to see the exact command you are using to run the script with all arguments. Looking back, I think you actually ran this: `./loadAndRunWorkspace.sh https://github.com/prathjan/iks-intersight-terraform.git`.  Correct? (That had not been entirely clear to me from your second post because your GH repo was on a second line.)

However, after looking at your actual variables.csv file in https://github.com/prathjan/iks-intersight-terraform/blob/main/variables.csv, I see that it does not include any value for api_key_id. Naturally, I understand why you have not included the actual value of that API key in your GitHub repository.  Are you running the script against an existing workspace in which the Terraform variable, api_key_id, already has a valid value?  If so, then I recommend removing api_key_id from your variables.csv file since having it there with no value (an empty string) is overriding any value you had already set in the workspace.

Of course, if you do remove api_key_id from variables.csv, then the initial running of the script would fail when the workspace did not already exist and have api_key_id set to a valid value. But future running of the script should then work since all variables would then have valid values.

While the script does support loading Terraform code and even variable values from a GitHub repository, it was originally written for use against Terraform code in the local config directory for which having variables with sensitive values like api_key_id in variables.csv would be ok since that file would only exist on your local machine and the value of the variable would not be shown in the Terraform Cloud UI since it would be marked as sensitive if you set the fifth column to `true`.

Another likely issue is that your variables.csv file is setting all the variables as environment variables in the third column by using `env`.  Terraform variables should be indicated with `terraform`.

Note that the readme.md has the following about variables.csv:
```
variables.csv which contains the variables that are uploaded to the workspace if no file with the same name is found in the root directory of the cloned repository. The columns are key, value, category, hcl, and sensitive with the last two corresponding to the hcl and sensitive checkboxes of TFE variables. This should be in the same directory as the script unless you include a file with the same name in your git repository.
```

The above documentation could be improved to indicate allowed values of `env` and `terraform` for the third column and `true` and `false` for the fourth and fifth columns, but the example file, https://github.com/hashicorp/terraform-guides/blob/master/operations/automation-script/variables.csv, does show the values `env`, `terraform`, and `false` from which the use of `true` could be extrapolated.

Also, please do note that in Terraform Cloud and Terraform Enterprise all environment variables need to be set in the workspace itself; they will not be picked up from your laptop where you run the script. So, if you are actually setting any env vars locally, but not in your workspace, either add them to your workspace or to variables.csv.

I hope that helps,
Roger

**Comment by rberlind** [comment]
Sorry, our responses crossed.  I wrote above before you sent your new post.

**Comment by prathjan** [comment]
@rberlind I manually added the api_key in TF Cloud GUI and marked it as sensitive...so its in the project.

This also fails though the variable has been defined:
./loadAndRunWorkspace.sh https://github.com/hashicorp/learn-state-migration
TFE_TOKEN environment variable was found.
TFE_ORG environment variable was set to CiscoDevNet.
Using organization, CiscoDevNet.
TFE_ADDR environment variable was not set.
Using Terraform Cloud (TFE SaaS) address, app.terraform.io.
If you want to use a private TFE server, export/set TFE_ADDR.
Cloning from git URL https://github.com/hashicorp/learn-state-migration into directory learn-state-migration
Using workspace set in the script.
override not set on command line. Will not override.
Tarring configuration directory.
Checking to see if workspace exists
Workspace ID: ws-GmAhz1KFwZ45b5Pd
Workspace already existed.
Creating configuration version.
Config Version ID: cv-NCfdqLgLE7PzDiHs
Upload URL: https://archivist.terraform.io/v1/object/.........
Uploading configuration version using learn-state-migration.tar.gz
Did not find variables.csv in configuration.
Will load variables from ./variables.csv
Adding variable name with value Roger in category terraform with hcl false and sensitive false
Adding variable TF_CLI_ARGS with value -no-color in category env with hcl false and sensitive false
Number of Sentinel policies: 0
Run ID: run-Xs35Tp8CKFrMJCmr
Checking run status
Run Status: errored
Run can be applied: False
Plan errored or hard-mandatory policy failed
Getting the result of the Terraform Plan.
Plan Log:
Terraform v0.11.14

Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1):

Output:
2021/03/04 18:58:43 [DEBUG] Using modified User-Agent: Terraform/0.11.14 TFC/c998a84844
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /terraform/main.tf: At 9:15: Unknown token: 9:15 IDENT var.name_length

Finished

**Comment by rberlind** [comment]
OK. Glad to hear you have your api_key_id variable set in your workspace. But please do note what I wrote about your having set all variables in your variables.csv file as "env".  Based on your variables.tf and on the fact that your are using Cisco's Intersight provider (https://registry.terraform.io/providers/CiscoDevNet/intersight/latest), I believe all of them need to be Terraform variables and then marked "terraform" and that you should therefore not include `api_key_id` or at least not with no value since that will override the value you have set in your TFC workspace. 

Also, be sure that you have set any of your Terraform variables that you did set in your workspace  under the "Terraform variables" section and not under the "Environment variables" section.

Also, it seems that your first variables in variables.csv is "endpoint" when it should be "api_endpoint" to match what you have in your variables.tf file. But since that variable has a default value, it probably is not causing problems.

Also, I see that variables.csv does not have `api_private_key`; have you set it in your workspace as a Terraform variable? Same for "mgmtcfgsshkeys".

Regarding your use of the https://github.com/hashicorp/learn-state-migration/blob/master/main.tf example, you would obviously need to use a different variable name and value for that than for your own Terraform code or for the example I provided with my script.  Since you cannot add a variables.csv file to that repository, what you should do is edit the one in the same directory as my script to use the following:

```
name_length,4,terraform,false,false
```
(or some integer other than 4 such as 2 or 3 or 5).

That will work because if the script does not find variables.csv in the repository (and copy to the directory named after it), it used the local copy from the same directory as the script itself.

Another issue is that the script is hard-coding the Terraform version to 0.11.14.  But if you use Terraform code constructs that require newer versions, that won't work.  And the example you picked does use newer syntax from 0.12 or 0.13. So, please try changing the version on line 119 to something like 0.13.6. Changing to that version after having changed the local variables.csv worked for me.  I got the following:

```
TFE_TOKEN environment variable was found.
TFE_ORG environment variable was set to Cloud-Operations.
Using organization, Cloud-Operations.
TFE_ADDR environment variable was not set.
Using Terraform Cloud (TFE SaaS) address, app.terraform.io.
If you want to use a private TFE server, export/set TFE_ADDR.
removing existing directory learn-state-migration
Cloning from git URL https://github.com/hashicorp/learn-state-migration into directory learn-state-migration
Using workspace set in the script.
override not set on command line. Will not override.
Tarring configuration directory.
Checking to see if workspace exists
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'data'
Workspace ID: 
Workspace did not already exist; will create it.
Workspace ID:  ws-KaesNfqJP2wmcVm2
Creating configuration version.
Config Version ID:  cv-9MtmgbkLUmt3SXNy
Upload URL:  https://archivist.terraform.io/v1/object/dmF1bHQ6djE6TExZUTVhWlNUQVhOMDduYURwQzArR1BtK3E5OWlrZ0MvS3J1Nmg3YnhZNVloS3JwZUlGK0hmQ2dwWER3Wkc4K1RLVndXa2xxczlhOE5IT0JwVHFWMkgrQ2VpRG1qb0ZCd0UyM3dIUXBsUDVYbFB5TW5sMVVnbDhjTlBPTEJYVERXcXQyWUtiTEVOM1BUTmoza0t0NEE1eHNpeGlmVEpWNTd4ck0ySnI2TVA3VlNwMkdJR2hPZGtMZlVyWnpoT0VuNVFOZjJJVjV0clVIMlpUV1hPZzRxWXdkOEdUancwR0VOT2JXd0NyRTNxWk5hZWtjSmlja2FmNjRXMVVEOUJzOFFqbW4yc3NMVTNoVC8zcTBKMUN4OENRa3krb3pJWkU9
Uploading configuration version using learn-state-migration.tar.gz
Did not find variables.csv in configuration.
Will load variables from ./variables.csv
Adding variable name_length with value 4 in category terraform with hcl false and sensitive false
Number of Sentinel policies:  17
Run ID:  run-sY3Qe2ARpP8WQCqd
Checking run status
Run Status:  planning
Run can be applied:  False
We will sleep and try again soon.
Checking run status
Run Status:  cost_estimating
Run can be applied:  False
We will sleep and try again soon.
Checking run status
Run Status:  cost_estimated
Run can be applied:  True
We will sleep and try again soon.

etc.
```

I then was able to manually apply the run. But I had to use <ctrl>-C to terminate the script at that point.

However, I then deleted my workspace and ran `./loadAndRunWorkspace.sh https://github.com/hashicorp/learn-state-migration "" yes` with the extra "yes" parameter to indicate that I wanted to automatically apply if there were no Sentinel violations and to override any soft-mandatory Sentinel violations.  Note, however, that this only works currently if cost estimates are disabled for the organization since the script was written before cost estimates were added to TFC/E and is not checking for the status "cost_estimated".  I can fix that in the near future.  For now, please disable cost estimates in your organization.

Please note that I wrote that script almost 3 years ago. It is only intended as an example.  Even after I got the apply to run, I still saw some errors related to retrieving the first state file from the run at the end of the script.  In fact, I believe TFC used to give two state files at the end of a run, the old one and the new one; but it now appears to only give the new one.

Also, note that changes to variables.csv does not trigger actual changes to existing variables.  That is because the API for updating a variable is different from the API for creating one.  If you add `echo "upload variable result: $upload_variable_result"` after uploading a variable on line 251, you'll see something like this:

```
upload variable result: {"errors":[{"status":"422","title":"invalid attribute","detail":"Key has already been taken","source":{"pointer":"/data/attributes/key"}}]}
```

If you want to run the script and change variables, you would have to delete the variables being changed.  Note that I did also write scripts to create and delete variables from workspaces under https://github.com/hashicorp/terraform-guides/tree/master/operations/variable-scripts.

Again, please keep in mind that the script was never really intended to be used with real world workspaces and repeated runs with changing variables.  It was really just meant to illustrate how the various TFC/E APIs can be used.  I'll make changes that I can easily make to make it work with newer versions of TFC, but you might ultimately have to make your own changes to make it fully meet your needs.

Roger

**Comment by prathjan** [comment]
@rberlind I added to variables.csv, deleted the workspace, changed version to 0.13.6. But,
./loadAndRunWorkspace.sh https://github.com/hashicorp/learn-state-migration
TFE_TOKEN environment variable was found.
TFE_ORG environment variable was set to CiscoDevNet.
Using organization, CiscoDevNet.
TFE_ADDR environment variable was not set.
Using Terraform Cloud (TFE SaaS) address, app.terraform.io.
If you want to use a private TFE server, export/set TFE_ADDR.
removing existing directory learn-state-migration
Cloning from git URL https://github.com/hashicorp/learn-state-migration into directory learn-state-migration
Using workspace set in the script.
override not set on command line. Will not override.
Tarring configuration directory.
Checking to see if workspace exists
Workspace ID:  ws-GmAhz1KFwZ45b5Pd
Workspace already existed.
Creating configuration version.
Config Version ID:  cv-JUZ2MABqkdcKxx4z
Upload URL:  https://archivist.terraform.io/v1/object/dmF1bHQ6djE6VWNDN1BteDVZYUtUNXVIaFFUWW9CVElZMHZVM1QxLzRtS0wySzJ2UXJMMkxEcUowQ3RqNERlZVBoSWUzTkNMYnJKa2FEZDRNeTc0dHNyRXZOdkpVVXpiSGZGb1NQU1A5UXUrWGlNbWRlV3J3S0U2elFsMURNTkplbTVXMUlNQ1UzbzFnK1NyVW5VLzV1cTFQaW16dStNVDZPTWxnZDJGZ1J1ZXNreFJvRFVscUwxVHZkK0NRZ1JHdlN2SGVTVm0vY05mNlMzWWhLVEllRElQRFNGLzFHUmtIQkdGSmdySHA4QUJPSXZZZHYzNzhZMytIbEFMZUlYSHdrczhjS1htdXVFSGttZVhCcFZTa3M0T2gycURPQmtNWjh6SGNqTmM9
Uploading configuration version using learn-state-migration.tar.gz
Did not find variables.csv in configuration.
Will load variables from ./variables.csv
Adding variable name with value Roger in category terraform with hcl false and sensitive false
Adding variable name_length with value 3 in category terraform with hcl false and sensitive false
Adding variable TF_CLI_ARGS with value -no-color in category env with hcl false and sensitive false
Number of Sentinel policies:  0
Run ID:  run-AAktfCFV2Rzoee4T
Checking run status
Run Status:  errored
Run can be applied:  False
Plan errored or hard-mandatory policy failed
Getting the result of the Terraform Plan.
Plan Log:
Terraform v0.11.14

Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2021/03/04 22:57:41 [DEBUG] Using modified User-Agent: Terraform/0.11.14 TFC/c998a84844
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /terraform/main.tf: At 9:15: Unknown token: 9:15 IDENT var.name_length


Finished

**Comment by rberlind** [comment]
@prathjan : I did a PR to update my script so that it now does work if cost estimates are enabled in the TFC org.  I also updated it to only download 1 state file since TFC no longer lists the before and after state files for runs. I believe everything is working correctly with my script now.  I also just did a second PR to print out the workspace name so that I can see when helping customers what workspace name they might have set in the script if they did not pass it into the script as an argument.

Regarding your run with `./loadAndRunWorkspace.sh https://github.com/hashicorp/learn-state-migration "" yes`, I see that it is still loading a variable called `name` with value `Roger` in addition to the `name_length` variable with value 3. Having the extra variable does not actually matter, however, which I just verified by testing.

I suspect that the problem here is that your TFE_TOKEN is somehow not valid for your organzation.  Your log shows that the script could not create the workspace. Your token should either be your own user token or a team token for the owners team of your organization.

Given that your token did let you complete some API calls successfully when the workspace already existed, I suspect that your token does not have the ability to create workspaces.

Unfortunately, since the script is now working correctly, I cannot do additional debugging on this issue unless you show convincing evidence that the script still needs fixes.  Even then, it could take me some time to make those fixes since I have other work that I must complete and this script is an unsupported example.

Fortunately, my colleague Vinnie Ramirez has reached out to you to connect you with TFC experts within your own company. So, I am confident that with their help, you will eventually get this all working correctly.

Please do update this ticket when you get it working or if you find clear evidence of problems in the script. For now, I'll leave the issue open.

Roger Berlind

**Comment by rberlind** [comment]
Note that you need a TFC/E token from the owners team or your organization or from a team that has the "Manage Workspaces" organization permission within that organization in order to create a workspace with the API.

**Comment by rberlind** [comment]
I'm actually going to close this issue for now, @prathjan . You can re-open if needed.
