### ISSUE TITLE
Move Sentinel common functions to another repository

### ISSUE THREAD

**Issue by AndriiChuzhynov** [hashicorp/terraform-guides#282]
Hi! I'm working with Sentinel now and noticed that this repository contains well-defined and tested functions which can be used in different projects.
I'd like to use it in my project as remote modules like it's done [here](https://github.com/hashicorp/tfc-workshops-sentinel/blob/master/aws/sentinel.hcl#L6).

But the name of this repository means that it's the right place to set dependencies for. 

What do you think about creating a new repository only for Sentinel common-functions? 
To allow users to set dependencies and get updates easily.

**Comment by rberlind** [comment]
Thanks for the suggestion @AndriiChuzhynov and apologies for taking so long to respond to you.
I would rather not move the common functions to a different repository since they have been in this one for a long time and is where people look for them. However, when you refer to a module like tfplan-functions, there is nothing preventing you from referring to it with a remote source just like I did in the example you gave.
