### ISSUE TITLE
Missing `--request POST`

### ISSUE THREAD

**Issue by 2stacks** [hashicorp/terraform-guides#302]
https://github.com/hashicorp/terraform-guides/blob/fcdf2678c4d101672fa260e5d59757fa438c2fd2/operations/automation-script/loadAndRunWorkspace-jq.sh#L218

**Comment by rberlind** [comment]
Thanks for creating this issue, @2stacks .  While `--request POST` could certainly be added, it is not required since POST is implied by the use of `--data`.  Note that there are other curl requests that also use `--data` without `--request POST`.  If we were going to add it, I would want to add it in all cases in bothe the python and jq versions of this script.  But it is not really needed.
