### ISSUE TITLE
Publish a release?

### ISSUE THREAD

**Issue by xbalajipge** [hashicorp/terraform-guides#315]
I would like to use the `tfplan-functions` and the like in  sentinel policies with direct references, similar to one as seen here https://nicovibert.com/2020/10/05/first-look-into-hashicorp-sentinel-and-policy-as-code-part-2/ 

like
```
module "tfplan-functions" {
    source = "https://raw.githubusercontent.com/hashicorp/terraform-guides/master/governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel"
}
 
module "tfstate-functions" {
    source = "https://raw.githubusercontent.com/hashicorp/terraform-guides/master/governance/third-generation/common-functions/tfstate-functions/tfstate-functions.sentinel"
}
 
module "tfconfig-functions" {
    source = "https://raw.githubusercontent.com/hashicorp/terraform-guides/master/governance/third-generation/common-functions/tfconfig-functions/tfconfig-functions.sentinel"
}
```

When I looked at this repo, there are no releases published, is it possible to publish a release it is not pointing to a moving branch (master). Thanks!

And if this not a recommended practice please let me know.

Thanks!
Balaji

**Comment by rberlind** [comment]
@xbalajipge : we have never created releases for this repository, but it should not be necessary for purposes of using Sentinel policies in it since when you register one of the Sentinel policy sets such as https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/aws/sentinel.hcl in a TFC/E organization, you can specify a branch.  So, if you don't want to use the latest version of these policies, create your own fork and then create a branch indicating the time when it was created. You can then later create more branches with updated code from this repo.  Even if we did create releases for this repo, it would not help you since the process of registering a policy set in a TFC/E organization does not let you specify a tag or a release. See https://www.terraform.io/cloud-docs/sentinel/manage-policies#managing-policy-sets.

I should note that the Sentinel policy sets in TFC/E are automatically updated as changes are made in the branch that they point to.  The git commit is even shown.  That is probably why we do not let you specify a git commit or tag/release when registering the policy sets since the design assumes you want your policy sets updated as changes are made.

Note that registered policy sets do show the git commit for the

**Comment by rberlind** [comment]
@xbalajipge : Please note that in response to another issue, I have copied all the third generation policies from this repository into a dedicated repository just for Sentinel policies for TFC/E, https://github.com/hashicorp/terraform-sentinel-policies.  In that repository, I did create a v1.0.0 release.  But I did that more for versioning reasons and still don't think it will help you with regard to registering policy sets from the new repository or from your own fork of it in Terraform Cloud or Terraform Enterprise organizations.

**Comment by xbalajipge** [comment]
Thank you, much appreciate the quick response. We are using the common functions in our policies, we want to avoid duplicating and pin it to a released version something like below.
```
module "tfplan-functions" {
    source = "https://raw.githubusercontent.com/hashicorp/terraform-sentinel-policies/v1.0.0/common-functions/tfplan-functions/tfplan-functions.sentinel"
}
```

**Comment by rberlind** [comment]
Thanks @xbalajipge :  That does now make sense.  I had been thinking of releases in terms of registering entire policy sets with Terraform Cloud or Terraform Enterprise.  Releases would not help with that.  But will help with pointing policy sets in other repositories against a specific release of the terraform-sentinel-policies repository.
