### ISSUE TITLE
Add Sentinel tests for all policy examples

### ISSUE THREAD

**Issue by jcmcken** [hashicorp/terraform-guides#64]
Would you be able to provide test case JSON files for all of the example Sentinel policies in this repo? I think it would be helpful for policy developers

**Comment by robertpeteuil** [comment]
If you have TFE, you might find value from the tests in [tfe-policies-example](https://github.com/hashicorp/tfe-policies-example).  

Many of the policies are similar, but names & organized differently.  It also incorporates a CI process using GitHub actions.

**Comment by rberlind** [comment]
@jcmcken and @tomisaacson : Alot changed since the earlier posts.
All second and third generation Sentinel policies in this repo DO have test cases.
The second generation policies have JSON test case files.
The third generation policies used to have JSON test case files, but they now use the newer HCL test case file format instead.

Roger Berlind
Global Technology Specialist
HashiCorp

**Comment by amitkumardube** [comment]
If I am not using Terraform enterprise then how can I use sentinel with Terraform CLI?
The way I tried is using **terraform show -json <plan file>** but then I get json output which I don't know how to use as mock with sentinel configuration file during **sentinel apply**

**Comment by rberlind** [comment]
@amitkumardube : the third generation example policies and common functions in this repository are definitely intended to be used with Terraform Cloud and Terraform Enterprise since they rely upon the Terraform-sprecific Sentinel imports listed [here](https://www.terraform.io/docs/cloud/sentinel/import/index.html).  When using TFC or TFE, one generates [mocks](https://www.terraform.io/docs/cloud/sentinel/mock.html) and then references them in test cases used by the Senitnel CLI.  It is possible to use the Sentinel CLI against the output of `terraform show -json`, but you would need to populate [global](https://docs.hashicorp.com/sentinel/configuration#global-1) data within the configuration file or use the `-global` command line argument to populate that data.

You might be able to tweak my tfplan-functions  module and the policies in this repository that use it to work against the output of `terraform show -json`. But it would be simpler to open a Terraform Cloud account and then subscribe to the Team & Governance module so that you could use Sentinel and the Terraform-specific Sentinel imports in TFC. See https://www.hashicorp.com/products/terraform/pricing

**Comment by amitkumardube** [comment]
Thanks @rberlind for quick response.
I used terraform enterprise with sentinel(with 3rd generation policies) in my past organization and they work pretty well. I was quite impressed with the build time monitoring that sentinel offers and it's out of box support with TFE.
Recently I started a new role and they don't use TFE/TFC. While I am trying to convince them to go for these products it might take longer. 
In the mean time I am looking for a solution using terraform CLI and sentinel CLI. I need a flow like below in CI/CD.
- **terraform plan** -> **terraform show -json** -> sentinel check as per the policies/policy set written -> If all good then **terraform apply**.
Do you have some working examples on how I can use the output of terraform show -json output as Global in the configuration without any manual interference ?
or Any clue on what needs to be changed in your tfplan-functions to use output of **terraform show -json**. 

Appreciate your help. Thanks

**Comment by rberlind** [comment]
@amitkumardube :  Unfortunately, I do not have any working examples that do what you want. But I can make the following more detailed suggestions for how you would do it while using modified versions of my third-generation common functions:

1. Extract the `resource_changes` portion of the plan.json output returned by `terraform show -json` into a variable and pass that into the `-global` argument of the `sentinel apply` command or insert it into the `global` section of a Sentinel CLI configuration file used with the `sentinel apply` or `sentinel test` command.
2. Modify the find_resources and similar functions in my tfplan-functions.sentinel Sentinel module to also include a `resource_changes` argument.
3. Also change occurences of tfplan.resource_changes to resource_changes.
4. You will also have to make some changes in the tfplan-functions.sentinel code to deal with the fact that the resource_changes global will be a list indexed by integers which means that the address iterator will not give the actual address of each resource.  I suggest changing occurences of address as a iterator variable in the filter functions to index and then changing other occurences of address to rc.address to get the actual address from each resource change.
5. When calling the find functions, pass the `resource_changes` global into them.

**Comment by amitkumardube** [comment]
thanks @rberlind . I will try this out in upcoming days and update here whether or not I get it working. 
Thanks for you time and help.

**Comment by amitkumardube** [comment]
@rberlind - I did the necessary adjustments and got **sentinel apply** working. Thanks for your continuous help.
Unfortunately I couldn't get **sentinel test** working. The error is not descriptive and verbose flag doesn't add anything extra. Below is the error.
C:\Users\User\Downloads\terraform_0.14.4_windows_amd64\sentinel>sentinel test check_secret.sentinel
**Error loading policies in check_secret.sentinel: 0 errors occurred:**

This is my command function - https://github.com/amitkumardube/sentinel/blob/main/common-functions/tfplan-functions/tfplan-functions.sentinel
and test cases can be found at https://github.com/amitkumardube/sentinel/tree/main/test/check_secret

Any clue about what could be wrong ? Thanks again.

**Comment by rberlind** [comment]
@amitkumardube : apologies for the delay getting back to you.
I believe the problem is that your test cases should have `../../../common-functions/tfplan-functions/tfplan-functions.sentinel` instead of `./../../common-functions/tfplan-functions/tfplan-functions.sentinel`.

Roger

**Comment by amitkumardube** [comment]
thanks @rberlind for our response. Though the path was looking ok , I tried your suggestion but the error remains.

C:\Users\User\Downloads\terraform_0.14.4_windows_amd64\sentinel>sentinel test check_secret.sentinel
Error loading policies in check_secret.sentinel: 0 errors occurred:

this is how module source looks now.
    "module" : {
        "tfplan-functions" : {
            "source" : "../../../common-functions/tfplan-functions/tfplan-functions.sentinel"
        }
    },

Appreciate your help. Thanks
